Switched font, various other changes

diff --git a/.scripts/apply_cpro_devpath b/.scripts/apply_cpro_devpath
--- a/.scripts/apply_cpro_devpath
+++ b/.scripts/apply_cpro_devpath
@@ -1,5 +1,22 @@
 #!/usr/bin/env sh
 
+get_devnum() {
+  if [[ -d "/sys/class/hwmon" ]]; then
+    for dev in /sys/class/hwmon/*; do
+      dev_name=$(sed -e 's/[[:space:]=]/_/g' $dev/name)
+      if [[ "$dev_name" == "corsaircpro" ]]; then
+        echo $dev | sed 's/\/sys\/class\/hwmon\/hwmon//g'
+        exit 0
+      fi
+    done
+    echo "Error: \"corsaircpro\" device not found."
+    exit 1
+  else
+    echo "Error: /sys/class/hwmon/ does not exist."
+    exit 1
+  fi
+}
+
 get_devpath() {
   if [[ -d "/sys/class/hwmon" ]]; then
     for dev in /sys/class/hwmon/*; do
@@ -17,6 +34,6 @@ get_devpath() {
   fi
 }
 
-sudo sed -i "s/hwmon4=devices.*$/hwmon4=$(get_devpath | sed 's/\//\\\//g')/g" /etc/fancontrol
+sudo sed -i "s/hwmon$(get_devnum)=devices.*$/hwmon$(get_devnum)=$(get_devpath | sed 's/\//\\\//g')/g" /etc/fancontrol
 
 sudo systemctl restart fancontrol
